const posts = [
  {
    title: 'Polishing the Finish Line',
    date: 'April 2026',
    body: `Recently, I have been spending a lot of time working on my final presentation and improving my portfolio. Since both of these represent the work I have done over a long period of time, I wanted to make sure they looked polished, organized, and professional. My final presentation is especially important because it brings together everything I have learned, researched, and created. I have been focusing on making the slides cleaner, improving the flow of information, and making sure each part clearly explains my project and its progress. At the same time, I have also been updating my portfolio so it better reflects my growth and the quality of my work. I have been revising descriptions, reorganizing sections, and making the overall design look stronger and more appealing. I want my portfolio to not only show what I have completed, but also present it in a way that is easy to understand and visually engaging. This process has made me realize how important presentation is. Even strong work can be overlooked if it is not displayed clearly. Working on both the presentation and portfolio has taken patience and attention to detail, but it has also been rewarding. It feels good to take the final steps in making my work look its best. Overall, this stage has been about refining, improving, and making sure my final products truly represent the effort I have put in.`,
  },
  {
    title: 'How a Mentor Meeting and Final Preparations Shaped My Growth',
    date: 'April 2026',
    body: `This week was a productive one filled with meaningful reflection and hands-on work. I had the opportunity to meet with my mentor, and it turned out to be one of the most valuable conversations I've had throughout this entire process. We spent a significant amount of time discussing development in the artificial intelligence field, exploring current trends, emerging tools, and where the industry is heading. It was fascinating to hear their perspective and gain insight into areas I hadn't fully considered before.

Beyond that broader discussion, we also took the time to evaluate my overall project from start to finish. My mentor offered honest, constructive feedback that helped me recognize several flaws in my process. While it was humbling to hear, I genuinely appreciate the critique because it gave me a clear picture of what I can improve and fix next time around. Having someone experienced point out those weak spots made a real difference in how I plan to approach future projects.

In addition to the mentor meeting, I stayed busy with other important tasks. I worked on passing out final presentation invitations to make sure everyone who needs to attend is informed and prepared. I also dedicated time to creating my classroom program, which required careful planning and attention to detail. Overall, it was a week of growth, preparation, and learning from feedback.`,
  },
  {
    title: 'Progress Through Mentorship, Final Product Completion, and Reflection',
    date: 'March 2026',
    body: `Over the past couple of weeks, I have continued working toward my goals, even when things didn't go exactly as planned. During spring break, I intended to begin documenting my experience with a mentor. However, my mentor was unavailable at the time, which delayed that process. Instead of falling behind, I adjusted my plan and decided to be working with my mentor this week. This experience has already taught me the importance of flexibility and adapting to challenges in a professional setting.

Despite that setback, I made strong progress in other areas. I officially finished developing my final product, which is my waste detection model. Completing this project was a big milestone for me, as it represents all of the research, testing, and effort I have put in throughout the course. After finishing it, I began preparing a script for Final Product Night. I am focusing on clearly explaining my process, the purpose of my model, and how it can make an impact.

In addition, I completed Assessment 15, which is my final product proposal. This helped me reflect on my work and explain the decisions I made during development. I also updated and finished my product log, which documents my progress and keeps everything organized. Another thing was attending the district showcase, where I saw many creative and impressive projects. It was inspiring to see how other students approached their work. Afterward, I completed a reflection assessment over the experience, which helped me think more deeply about my own project and presentation.`,
  },
  {
    title: 'Progress Through Presentations, Assessments, and Final Product Development',
    date: 'February 2026',
    body: `Over the last couple of weeks in ISM, I have been working really hard to achieve all of the learning goals that I had set out for myself. My main tasks over this time have included finishing off Assessment 14 and 15, finalizing my presentation for my practicum, getting ready for the UofM showcase, and finishing my final product. I have been trying to balance out getting all of the work needed to do the assessments done, so that I can move into the next stage of my learning. For example, I have been relating my learning to my project and explaining how my work for the assessments will relate to my final product. The assessments are also a great summary of what I have been doing so far and are helping me to organize my thinking.

I finished all of my assessment that was due and started getting prepared for my practicum presentation. I've been thinking about how I'm going to present my practicum information in a way that is clear, professional and confident. A big part of this is thinking about how I can make my practicum material easy to understand for anyone that I may present to. Reflecting on my own learning and thinking about what is important to communicate has been really helpful. Also thinking about how to communicate the information from my research and product development activities in a meaningful way to non-experts has been valuable.

This week has been a bit of a mix of things. I have been getting ready for our upcoming showcase, and I have been thinking about how I will share my project with the public. I have been trying to decide how I will show off the best parts of my project, how I will write about my experience creating it, and making sure it is presentable for a professional setting. I am still working on finishing my final product, but I can see it getting closer to being completed with each step I take. I am feeling confident that I will be able to create something truly valuable and impactful.

Although I feel that I have done a lot of work for this week, I could still use some mentorship. The more feedback I receive, the better I will understand the project, and the better my product will be. This week has been very productive. I finished a few of the larger assignments, started preparing presentations and exhibits for the ISM showcase, and have been continuing to work on my final product. I could still use a mentor for this.`,
  },
  {
    title: 'Research Mania in ISM',
    date: 'January 2026',
    body: `This week, I focused on conducting in-depth research on waste detection models while also developing a stronger understanding of how to critically read and annotate academic articles. I explored various approaches used in waste detection, particularly those involving computer vision and machine learning, and examined how different models are trained to identify and classify waste in diverse environments. To ensure I fully understood the material, I carefully annotated each article I read by highlighting key ideas, summarizing methodologies, and writing notes about the strengths, limitations, and real-world applications of each model. This process allowed me to move beyond surface-level understanding and truly engage with the technical details presented in the research. As I continued reading, I began to notice common patterns across articles, such as the importance of high-quality datasets, accurate labeling, and evaluation metrics in determining model performance. Throughout the week, I also made a consistent effort to reach out to mentors for guidance and clarification. I asked questions when concepts were unclear and sought feedback on which research directions were most valuable to pursue. These conversations helped refine my understanding, corrected misconceptions, and gave me confidence in navigating complex material. Overall, this week was productive because it strengthened both my technical knowledge of waste detection models and my ability to deeply analyze and learn from academic research through structured annotation and mentorship.`,
  },
  {
    title: 'ISM in the SNOW',
    date: 'January 2026',
    body: `For the past few weeks in ISM, I have done 2 research assessments as well as my product log. The product log rough draft allowed me to really explore and brainstorm my final product ideas on how I will develop it. This also gives me a chance to obtain feedback on my product development for areas I can improve, so later on for my final draft of my product proposal I can write it with the feedback, improving my ideas. Additionally the 2 research assessments allowed me to explore YOLO architecture in my waste detection model I've currently developed. Some key issues that have begun to happen while I've been developing my model is an inaccuracy with some classification categories. Specifically, after I pre-label my training images on the yolo architecture often times there a huge inaccuracies, that though might be due to inaccurate labeling or quality images by me, but most likely there's something in the yolo architecture that is causing this error. The articles I annotated went on about this topic of how to make yolo classification more accurate which I'm now incorporating into my model. Finally the research showcase at Reedy went well, my boards could have improved some more in terms of design and consistency, but overall many people came to my board and were interested in my topic. However, the winter storm cancelled the symposium research showcase which is disappointing, but was probably the safest option. As of right now, I am contacting more professionals, hopefully having the chance to obtain mentorship.`,
  },
  {
    title: 'Board Building',
    date: 'December 2025',
    body: `Since before winter break to now, I've been working on designing my display boards on Canva in order to get a good idea on how it would look on real paper. Planning early on can prevent potential future mistakes by catching them early on while designing and can help me create a clear structured schedule to built my real boards. This is as I can use specific parts of my Canva design as milestones when I built my real boards. Additionally, I've started to research more papers and articles to strengthen my original work idea. Specifically the papers go on about how waste model detection software needs a larger amount of data to be more accurate on higher version Yolo models for more accuracy. ON top of this, I've also began to reach out to more potential mentor candidates and maintain communication them, people who are experiences in the machine learning field. However this past week I got really sick which caused me to fall behind a lot on my ISM work. As of right now, I still need to complete 3 assignments and my display boards which will be a little hectic, but it is possible. I will try my best to stay on top of my work and prepare for the January 23rd showcase and January 28th Comerica.`,
  },
  {
    title: 'My Original Work Structure Building',
    date: 'November 2025',
    body: `This was my week in ISM, where I worked on converting my Original Work into a plan of action by doing the Original Work Part 3 and AOL 9 as well as working on my ISM presentation. In Part 3, I drew the overall flow of my plastic waste classification model, how I will capture images each type of waste, how I will label and store my images and what baseline model architecture I will test before adding other complex features such as polarization. I also made a realistic schedule in which model training, evaluation, and hardware testing is spread over the course of the next few months so that I do not cram everything at the end. AOL 9 also assisted me in relating my research to this plan. It told me how papers on the accuracy of classifications, the confusion of crumpled plastics, and resource efficient models are directly influencing the choices I make concerning dataset size, performance measures and implementation in low cost hardware to serve grocery stores. In addition to that, I was outlining my ISM presentation. I have developed a title, a mission statement, which is the application of machine learning to minimize the amount of plastic waste, and the introduction that is short yet clear enough to inform the people about what I am talking about without confusing them with technical phrases. I made slide notes on my background research, research assessments, Original Work plan and future steps and began to make notes on what I will say in each section. At the week conclusion, I felt that finally my project has a roadmap and I am much better equipped to report my progress to other people.`,
  },
  {
    title: 'New Insight for My Product',
    date: 'November 2025',
    body: `This past week in ISM, I have worked in sending cold emails to professionals in the field of machine learning, and developing my Original Work product. I have done a research assessment part 2 of my original work way earlier than due, allowing me to focus a lot more on actually creating my product. IN the research assessment I found an research article that talked about how to classify different types of plastic waste. When machine learning classification models try to classify plastic waste often times it gets confused whenever the plastic is crumpled and disfigured. This is the highest amount of error in my classification model, and if it can me mitigated the model with achieve 90%+ accuracy. The method the research paper talks about is polarization. Essentially it uses a special type of camera that notices differences in particles by using different light spectrums than we humans do, a broader wave length which reveals similarities across all plastics polarization. I will try using the polarization software when testing and measure the accuracy and precision of the model with or without as it is entirely possible that it could lead to other misclassifications. IN order to implement this in real time I will have to use a raspberry pi and run the camera software. I still have time to develop my product but I will need to finish the testing soon so I can work on developing the hardware for my waste classification model. As far as professionals have go, I have currently interviewed only one professional form New York. He was nice and informative but I would prefer a close mentorship perhaps in person. The other professionals I have emailed have not responded, so I might have to resort to cold calling if I don't get responses back.`,
  },
  {
    title: 'Developing my Original Work',
    date: 'October 2025',
    body: `This past week in ISM, I have worked on scheduling interviews with professionals, with the goal of getting possible mentorship, and creating my original work proposal. My proposal consists of building an AI model within the month of November and creating a website to explain the process to beginners in computer science or really any field who want to learn more about how AI is developed. I first need to gather the materials needed for start developing my original work, which in my case is online(coding the model, and feeding it data). On top of this I have been working on enhancing my website for clarity, readability, and aesthetics. I added a more section where people who visit my website can view my research assessments, weekly reports, and really all my ISM work and future ISM work. As far as scheduling interviews go, I have been having a little difficulty. This is because the professionals either didn't responded or my email went to spam. Nonetheless, I have sent a lot more this week so I am expecting to hear back from a few. For all the professionals I have cold emailed I jotted their name down on my contact log for future reference. Finally I have finished part 1 of my original work research assessment. On it I went through a research paper and talked about how specifically I'm going to use that information to develop my original work. I made annotations on a Kami document to show my thinking process. That's it for this week, some assignments I need to start working on in the future is my next research assessment and developing my Original work.`,
  },
  {
    title: 'Building My Digital Presence and Preparing for Professional Outreach',
    date: 'October 2025',
    body: `This past week, I made strong progress in developing both my professional image and my preparation for the next phase of my project. I established my digital portfolio through the creation of a customized website which displays my biography and present interests and all finished ISM assignments. The portfolio enables users to access my research assignments and previous weekly blog entries and reflection reports which demonstrate my increasing knowledge of machine and deep learning. The process of creating this website taught me effective methods to display my academic achievements and professional experience through a professional and easy-to-use interface. In addition to that, I finalized my cold emailing template and cold calling script that I will use once I begin contacting professionals in the industry. The class practice of these scripts with several classmates helped me develop communication skills while teaching me to modify my speaking tone for professional and interesting delivery. I searched for new professionals who work in my field to obtain their contact information which I added to my database. I started working on my Original Work Proposal which defines the core elements of my upcoming final project. The process enabled me to define my project's fundamental purpose and particular goals and work methods which will guide my work beginning now. The week brought me essential progress and self-assurance which will help me connect with professionals and develop my original research.`,
  },
  {
    title: 'New Connections',
    date: 'September 2025',
    body: `At the ISM Symposium I got to meet professionals, and new ISM students throughout Frisco, and the discussions allowed moving a loose set of ideas into a narrowed plan. The interview with Kishore Mahadev was interesting because he challenged me to consider the concept of efficiency as an objective, as well as accuracy, which is relevant to me in the field of deep learning adaptation techniques. Listening to the experiences of other students in the field of outreach and documentation also provided specific ideas on how to schedule the follow ups, maintain progress, and display my work in an uncomplicated way on my online portfolio. Researchwise I completed Research Assessment 4, making my variables and inclusion criteria more precise so that my source matrix will compare like with like. I was particularly concerned with the presentation in papers of compute and training schedules, since this has a direct bearing on any assertion about accuracy per compute. That clarity I made my topic proposal, which included a plan to experiment on small vision transformers to check the practicality of the methods of adaptation and to measure the performance with respect to the factors that are important to real users: accuracy per unit time or energy. This week will be the transition to the execution stage: there are mentors to get in touch with, datasets to complete; and a reproducible process to construct in order to start getting baseline results. The following week I will also send out follow up emails to possible mentors, secure my primary experiments, and post this update on my online portfolio allowing the stakeholders to get a glimpse of my direction and provide specific feedback.`,
  },
  {
    title: 'Building Skills and Connections',
    date: 'September 2025',
    body: `In the last two weeks of ISM, I aimed at consistent, in-practice achievements that will help me proceed with my deep learning project and prepare me professionally to attend Symposium. I categorized the sources of my gathering into distinct folders and brief outlines in order to be able to notice, at a first glance in my questions regarding forming vision models efficiency and reliability. I relied on those notes to create interview questions that will allow me to learn with people who are in this field. There are questions regarding their way, the manner in which they work, and what skills are indeed important. Other questions are devoted to Vision Transformers, the distinction between LoRA and linear probing, training under tight time and energy constraints, and the data on the measurements of results in an unbiased manner that incorporates both accuracy and latency and power consumption. I have also become more purposeful in networking where I identify the professors and professionals I am interested in and sending short and polite introductory messages and keeping a watch on responses so that I can follow up. We are training Symposium in the class that is a business style event where we train interviewing, networking, and I completed my resume with clean formatting, action verbs, and definite results of my projects. I also identified the most important skills in my topic such as Python, PyTorch, data manipulation and constraint-based evaluation. These actions brought me out of the abstract collection information stage to constructing a plan that I may employ. I can now boast of structured sources, targeted questions, expanding contacts and a resume that portrays me as a professional.`,
  },
  {
    title: "Rithvik's Early Steps",
    date: 'August 2025',
    body: `For past few weeks in ISM I have been able to develop my understanding in the study of deep learning as well as meet many new people with such keen interests to their topic sharing and receiving feedback. Specifically, through the ISM mini group discussions I have been able to get to know my classmates better and receive guidance from ISM 2 students on how to be successful in the ISM program. I have also been able to practice my presentation skills, and received beneficial feedback from Mrs. Russell and my classmates on what I did well but also what I can improve on to enhance my presentation abilities. Similarly, I have also been able to share and receive feedback on my resume which was very useful so I have an idea what an ideal one should look like for this class. The process of me giving feedback to my classmates whether it was on resumes or presentations has benefited me in a another way as it also makes me aware of common mistakes that I can avoid. Moving on to my development in the study of deep learning, I have annotated 4 documents, specifically about the efficiencies between two adaptation methods in Cifar-10 architecture, which helps me to develop to one of my smart goals which was to research and annotate 5 sources by September 23rd. This has allowed me to consider different viewpoints in my topic, and help me understand new ideas I may have to learn to be successful during my product development. One other benefit of annotating these documents was to get an idea on what type of emails I need to send to send professors to gain their interest as most of the people that write these papers are professors with vast experience, allowing me to understand innovations that are currently of interest to them. Finally the Career Outlook Assessment gave me the opportunity to test how passionate I am in the field of deep Learning by reflecting on my current knowledge and sharing my experiences with others.`,
  },
];

export default function Blog() {
  return (
    <main className="page-container">
      <h1 className="page-heading reveal">Blog</h1>
      <p style={{ color: '#555', fontSize: '0.75rem', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: '2.5rem' }}>
        Weekly reflections — newest to oldest
      </p>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
        {posts.map((post, i) => (
          <div key={i} className="content-card reveal">
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', flexWrap: 'wrap', gap: '0.5rem', marginBottom: '1rem' }}>
              <h2 style={{ fontSize: '1rem', fontWeight: 600, color: '#ddd', letterSpacing: '-0.01em' }}>
                {post.title}
              </h2>
              <span style={{ fontSize: '0.65rem', color: '#555', letterSpacing: '0.1em', textTransform: 'uppercase', whiteSpace: 'nowrap' }}>
                {post.date}
              </span>
            </div>
            {post.body.split('\n\n').map((para, j) => (
              <p key={j} style={{ color: '#aaa', lineHeight: 1.85, fontSize: '0.875rem', marginBottom: '1rem' }}>
                {para}
              </p>
            ))}
          </div>
        ))}
      </div>
    </main>
  );
}
